# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: illuwa
# "service" is the name of this project. This will also be added to your AWS resource names.
service: doctor-guide-api

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  profile: jurloogar
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - !GetAtt HospitalSafetydata.Arn
        - !Sub '${HospitalSafetydata.Arn}/index/*'
        - !GetAtt PharmacySafetydata.Arn
        - !Sub '${PharmacySafetydata.Arn}/index/*'

package:
  patterns:
    - '!node_modules/**'
    - '!*.ts'
    - '!tsconfig.json'
    - '!.git/**'
    - '!.vscode/**'
    - 'dist/**/*.js'

resources:
  Resources:
    HospitalSafetydata:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Hospital
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: HSPTL_CLSF_NM
            AttributeType: S
          - AttributeName: INST_NM
            AttributeType: S
          - AttributeName: EMRO_OPER_YN_
            AttributeType: S
          - AttributeName: ADDR_REGION
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: hospital-classification-index
            KeySchema:
              - AttributeName: HSPTL_CLSF_NM
                KeyType: HASH
              - AttributeName: INST_NM
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: hospital-name-index
            KeySchema:
              - AttributeName: INST_NM
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: emergency-room-index
            KeySchema:
              - AttributeName: EMRO_OPER_YN_
                KeyType: HASH
              - AttributeName: HSPTL_CLSF_NM
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: region-index
            KeySchema:
              - AttributeName: ADDR_REGION
                KeyType: HASH
              - AttributeName: INST_NM
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    PharmacySafetydata:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Pharmacy
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: INST_NM
            AttributeType: S
          - AttributeName: ADDR_REGION
            AttributeType: S
          - AttributeName: WKND_MDEXM_YN
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: pharmacy-name-index
            KeySchema:
              - AttributeName: INST_NM
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: pharmacy-region-index
            KeySchema:
              - AttributeName: ADDR_REGION
                KeyType: HASH
              - AttributeName: INST_NM
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: pharmacy-weekend-index
            KeySchema:
              - AttributeName: WKND_MDEXM_YN
                KeyType: HASH
              - AttributeName: INST_NM
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

functions:
  hospital:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /hospital
          method: get
  pharmacy:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /pharmacy
          method: get
