name: Build and Publish SDK

on:
  workflow_dispatch: # 수동 실행 옵션 유지 (버전 지정 없음)
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  # 1. 전용 작업 공간에서 SDK 빌드
  build:
    name: Build SDK
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      # 태그에서 버전 추출 (v 접두사 제거)
      - name: Extract version from tag
        id: extract-version
        run: |
          # 태그가 있는 경우 태그에서 버전 추출 (v 접두사 제거)
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            # 태그가 없는 경우 package.json에서 버전 가져오기
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      # 전용 작업 공간에서 SDK 빌드 (최적화된 방식)
      - name: Generate SDK in workspace
        run: |
          # SDK 생성
          pnpm build:api

          # package.json 동적 생성
          VERSION="${{ steps.extract-version.outputs.version }}"
          REPO_URL=$(node -p "require('./package.json').repository.url")

          cat > ./workspace/package.json << EOF
          {
            "name": "@julooga/doctor_guide_api_sdk",
            "version": "${VERSION}",
            "description": "의료정보를 제공하는 api 의 스웨거 sdk",
            "main": "api.ts",
            "types": "api.ts",
            "repository": {
              "type": "git",
              "url": "${REPO_URL}"
            },
            "author": "Julooga",
            "license": "MIT",
            "dependencies": {
              "axios": "^1.9.0"
            }
          }
          EOF

          echo "SDK generated with version ${VERSION}"

      # 빌드 결과물을 아티팩트로 저장
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk-build
          path: ./workspace

  # 2. 빌드 결과물을 dist 브랜치로 푸시
  # 2. 빌드 결과물을 dist 브랜치로 푸시 (개선된 방식)
  deploy-to-dist:
    name: Deploy to dist branch
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 기본 브랜치 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 히스토리 가져오기
          token: ${{ secrets.GITHUB_TOKEN }}

      # Git 사용자 설정
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # 빌드 아티팩트 다운로드
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: sdk-build
          path: ./sdk-artifacts

      # dist 브랜치 강제 재생성 (기존 브랜치 삭제 후 새로 생성)
      - name: Force recreate dist branch
        run: |
          # 로컬 브랜치 목록 확인
          echo "Current local branches:"
          git branch -a

          # 원격 dist 브랜치 존재 여부 확인
          if git ls-remote --heads origin dist | grep dist; then
            echo "Remote dist branch exists - will delete and recreate"
            
            # 원격 브랜치 강제 삭제 시도 (실패해도 계속 진행)
            git push origin --delete dist || echo "Failed to delete remote branch, continuing anyway"
            sleep 2  # 삭제 작업이 완료될 때까지 잠시 대기
          else
            echo "Remote dist branch does not exist - will create new"
          fi

          # 로컬에 dist 브랜치가 있으면 삭제
          git branch -D dist 2>/dev/null || echo "No local dist branch to delete"

          # 빈 dist 브랜치 새로 생성
          git checkout --orphan dist
          git reset --hard  # 작업 디렉토리 초기화

          # 아티팩트 파일 복사
          cp -r ./sdk-artifacts/* ./ || echo "No artifacts to copy"

          # 모든 파일 추가 및 커밋
          git add -A
          git commit -m "chore: update SDK to version ${{ needs.build.outputs.version }}" || echo "Nothing to commit"

          # 강제 푸시 (--force 플래그 사용)
          git push --force origin dist
          echo "Dist branch recreated successfully"

      # 태그 푸시 시 dist 브랜치에도 태그 생성
      - name: Create dist tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION="${{ needs.build.outputs.version }}"
          # 기존 태그가 있으면 삭제
          git push origin :refs/tags/dist-v${VERSION} 2>/dev/null || echo "No existing tag to delete"
          # 새 태그 생성 및 푸시
          git tag -f "dist-v${VERSION}"
          git push --force origin "dist-v${VERSION}"
          echo "Dist tag created successfully"

  # 3. dist 브랜치에서 GitHub Packages에 게시
  publish:
    name: Publish to GitHub Packages
    needs: [build, deploy-to-dist]
    runs-on: ubuntu-latest
    steps:
      # dist 브랜치 체크아웃
      - name: Checkout dist branch
        uses: actions/checkout@v4
        with:
          ref: dist

      # Node.js 및 npm 레지스트리 설정
      - name: Setup Node.js with registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@julooga'

      # GitHub Packages에 게시
      - name: Publish package
        run: |
          echo "@julooga:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          npm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
