name: Publish SDK to GitHub Packages

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  install:
    uses: ./.github/workflows/install-dependency.yml
  build-and-publish:
    needs: install
    runs-on: ubuntu-latest
    permissions:
      contents: read # 소스 코드를 체크아웃하기 위해 필요
      packages: write # GitHub Packages에 패키지를 게시하기 위해 필요

    steps:
      - name: Generate SDK
        run: pnpm build:api

      - name: Publish to GitHub Packages
        run: |
          # sdk 디렉토리에 .npmrc 파일 생성
          echo "@julooga:registry=https://npm.pkg.github.com/" > sdk/.npmrc
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> sdk/.npmrc

          cd sdk
          # .npmrc 파일에서 레지스트리 정보가 이미 설정되었으므로 --registry 플래그는 생략 가능하나, 유지해도 무방합니다.
          pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
