name: Publish SDK to GitHub Packages

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # 소스 코드를 체크아웃하기 위해 필요
      packages: write # GitHub Packages에 패키지를 게시하기 위해 필요

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate SDK
        run: pnpm build:api

      - name: write .npmrc
        run: |
          # sdk 디렉토리에 .npmrc 파일 생성
          echo "@julooga:registry=https://npm.pkg.github.com/" > sdk/.npmrc
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> sdk/.npmrc

      - name: Publish to GitHub Packages
        run: |
          cd sdk
          pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
